classes = ['Andean Guan_sound',
 'Andean Tinamou_sound',
 'Australian Brushturkey_sound',
 'Band-tailed Guan_sound',
 'Bartletts Tinamou_sound',
 'Baudo Guan_sound',
 'Bearded Guan_sound',
 'Berlepschs Tinamou_sound',
 'Black Tinamou_sound',
 'Black-billed Brushturkey_sound',
 'Black-capped Tinamou_sound',
 'Black-fronted Piping Guan_sound',
 'Blue-throated Piping Guan_sound',
 'Brazilian Tinamou_sound',
 'Brown Tinamou_sound',
 'Brushland Tinamou_sound',
 'Buff-browed Chachalaca_sound',
 'Cauca Guan_sound',
 'Chaco Chachalaca_sound',
 'Chestnut-bellied Guan_sound',
 'Chestnut-winged Chachalaca_sound',
 'Chilean Tinamou_sound',
 'Cinereous Tinamou_sound',
 'Collared Brushturkey_sound',
 'Colombian Chachalaca_sound',
 'Crested Guan_sound',
 'Darwins Nothura_sound',
 'Dusky Megapode_sound',
 'Dusky-legged Guan_sound',
 'Dwarf Tinamou_sound',
 'East Brazilian Chachalaca_sound',
 'Elegant Crested Tinamou_sound',
 'Emu_sound',
 'Great Tinamou_sound',
 'Greater Rhea_sound',
 'Grey Tinamou_sound',
 'Grey-headed Chachalaca_sound',
 'Grey-legged Tinamou_sound',
 'Highland Tinamou_sound',
 'Hooded Tinamou_sound',
 'Huayco Tinamou_sound',
 'Lesser Nothura_sound',
 'Little Chachalaca_sound',
 'Little Tinamou_sound',
 'Marail Guan_sound',
 'Melanesian Megapode_sound',
 'North Island Brown Kiwi_sound',
 'Orange-footed Scrubfowl_sound',
 'Ornate Tinamou_sound',
 'Pale-browed Tinamou_sound',
 'Philippine Megapode_sound',
 'Plain Chachalaca_sound',
 'Puna Tinamou_sound',
 'Quebracho Crested Tinamou_sound',
 'Red-faced Guan_sound',
 'Red-legged Tinamou_sound',
 'Red-throated Piping Guan_sound',
 'Red-winged Tinamou_sound',
 'Rufous-bellied Chachalaca_sound',
 'Rufous-headed Chachalaca_sound',
 'Rufous-vented Chachalaca_sound',
 'Rusty Tinamou_sound',
 'Rusty-margined Guan_sound',
 'Scaled Chachalaca_sound',
 'Slaty-breasted Tinamou_sound',
 'Small-billed Tinamou_sound',
 'Solitary Tinamou_sound',
 'Southern Cassowary_sound',
 'Speckled Chachalaca_sound',
 'Spixs Guan_sound',
 'Spotted Nothura_sound',
 'Tataupa Tinamou_sound',
 'Tawny-breasted Tinamou_sound',
 'Thicket Tinamou_sound',
 'Tongan Megapode_sound',
 'Undulated Tinamou_sound',
 'Variegated Tinamou_sound',
 'West Mexican Chachalaca_sound',
 'White-bellied Chachalaca_sound',
 'White-bellied Nothura_sound',
 'White-crested Guan_sound',
 'White-throated Tinamou_sound',
 'White-winged Guan_sound',
 'Yellow-legged Tinamou_sound']